### ISSUE TITLE
requirements.txt is a bit lengthy

### ISSUE THREAD

**Issue by tyday** [akulchhillar/Red-Blue#1]
I think you can safely wean it down to:
click==7.1.2
coolname==1.1.0
Flask==1.1.2
Flask-SocketIO==4.3.1
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
python-engineio==3.13.2
python-socketio==4.6.0
six==1.15.0
Werkzeug==1.0.1

**Comment by akulchhillar** [comment]
Hey thanks a lot! I was using python's traditional way of creating requirements.txt. Let me deploy the project using the above requirements and will update them in the repository if it works.

By the way, by any chance do you any way by which I can create a requirements.txt file for python which includes only the libraries which are used in the project?

Edit: Have a look at the file now. I have add a couple of other dependencies in the file to make it work on heroku

**Comment by tyday** [comment]
Are you using a virtual environment? If you use a virtual environment it basically sets up a clean environment for you to play in. Then you install the pip files you need. Then pip freeze > requirements.txt

If you need help with virtual environments, I'm sure I can find a decent tutorial/blog post.

ps. love your game. I'm trying to build an algorithm to play it. I was struggling with getting the socketio messages right until you posted your code.

**Comment by akulchhillar** [comment]
> Are you using a virtual environment? If you use a virtual environment it basically sets up a clean environment for you to play in. Then you install the pip files you need. Then pip freeze > requirements.txt
> 
> If you need help with virtual environments, I'm sure I can find a decent tutorial/blog post.
> 
> ps. love your game. I'm trying to build an algorithm to play it. I was struggling with getting the socketio messages right until you posted your code.

**Comment by akulchhillar** [comment]
Got it. Yeah if you could share a few links for working up with local environments that would be great

**Comment by tyday** [comment]
So, if you're running python 3 and using linux or mac you can simply type:
```python3 -m venv venv```
That will create the virtual environment
```source venv/bin/activate``` will activate the environment
```deactivate``` leaves it.

It can be done in windows cmd line or powershell, but I don't have any experience using those.

In depth tutorial. It's old, but updated https://realpython.com/python-virtual-environments-a-primer/

The python docs https://docs.python.org/3/library/venv.html

The second highest answer from this quora thread was pretty helpful, detailed and succinct
https://www.quora.com/What-is-difference-between-pip-and-pip3?share=1
> 
> Magnus Lyckå
> , Owner & Consultant at Thinkware AB (1998-present)
> Updated March 19, 2017 · Author has 361 answers and 1.3M answer views
> 
> Each time you install a Python package, it will be placed in the directory for one particular Python version. It’s even a bit more complex than you suggested, since you can have more than one Python 2 installation on your machine, and also more than one Python 3 installation.
> 
> Things can actually get a bit messed up, e.g. if you have some python libraries under /usr/lib and others under /usr/local/lib. If you get some strange import error about requests from pip, this is probably what happened.
> 
> The best way to handle things is probably to leave the OS python installations as pristine as possible, and then install the packages you want for your development in virtual environments.
> 
> Pip works as a module with -m, and so does venv for Python 3, so if you have Python 3.5 installed and stand in a project directory, you could e.g. do (assuming linux or MacOS):
> 
> $ python3.5 -m venv venv35
> 
> $ source venv35/bin/activate
> 
> (venv35) $ pip install <whatever>
> 
> That will install <whatever> in the Python3.5 virtual environment venv35 in your current
